### ISSUE TITLE
Bump RLIMIT_MEMLOCK automatically using libbpf

### ISSUE THREAD

**Issue by yanivagman** [aquasecurity/libbpfgo#102]
We now have our own implementation to bump the rlimit_memlock, which is required on older kernels (< 5.11).
libbpf recently merged https://git.kernel.org/pub/scm/linux/kernel/git/bpf/bpf-next.git/commit/?id=e542f2c4cd16 - this will allow us to remove our implementation and let libbpf to automatically set this limit on older kernels

**Comment by grantseltzer** [comment]
Handled by #225
