### ISSUE TITLE
Map iterator returns "no such file or directory" unexpectedly

### ISSUE THREAD

**Issue by kakkoyun** [aquasecurity/libbpfgo#114]
Error handling changes in https://github.com/aquasecurity/libbpfgo/pull/100, causes iterators to fail unexpectedly https://github.com/parca-dev/parca-agent/issues/213

https://github.com/aquasecurity/libbpfgo/blob/main/libbpfgo.go#L753-L759 

(I'm still investigating what's actually wrong, will send a fix I can find out)

**Comment by rafaeldtinoco** [comment]
We have reverted the error handling logic in commit https://github.com/aquasecurity/libbpfgo/pull/119 and will stabilize it before merging it again. Sorry for the inconvenience and closing this because of that reversion.
