### ISSUE TITLE
Verify checking of errno is correct low level APIs, and deprecation post 1.0

### ISSUE THREAD

**Issue by grantseltzer** [aquasecurity/libbpfgo#13]
Currently low level libbpf APIs, specifically APIs in [bpf.h](https://github.com/libbpf/libbpf/blob/master/src/bpf.h) use errno for representing errors. In 1.0 this will be completely removed and all error codes will be returned directly from API functions.

**Comment by geyslan** [comment]
Closing, as it was handled in #225.
