### ISSUE TITLE
BUG: perf_buffer__new API doesn't support old kernel versions

### ISSUE THREAD

**Issue by AlonZivony** [aquasecurity/libbpfgo#135]
@rafaeldtinoco commit `5e8900` solving #121 changed libbpf API.
As a result, building `Tracee` for kernel `v4.19.230` failed for me.
![error with libbpfgo kernel v4 19 230](https://user-images.githubusercontent.com/87267148/156371799-2b9d2905-8f6d-43bb-9ae3-cadd65e7644f.PNG)
`Tracee` suppose to support kernels down to `v4.18`, so it seems to me this commit breaks this assumption.

**Comment by rafaeldtinoco** [comment]
I'll take a look at this later today. We have to support 4.19 stable tree (from upstream) and RHEL 4.18 kernels (not quite 4.18, there are lots of changes) FYIO. It seems that you're using 4.19 stable tree version so we should support it, I'll check it.

**Comment by yanivagman** [comment]
I don't understand how can this be related to the kernel version. It only changed the API used from libbpf.
Can it be that for some reason your'e using an old version of libbpf?
I would also try to remove "dist" directory and make clean

**Comment by AlonZivony** [comment]
You are right, it was my mistake.
I just thought that because this is a new commit it might have caused the problem, but it was my fault for not doing `make clean`.
Thanks for the help!

**Comment by rafaeldtinoco** [comment]
I'm glad that was simple! Thanks @AlonZivony and @yanivagman .
