### ISSUE TITLE
How can we change the libbpf  log level ?

### ISSUE THREAD

**Issue by zhangbo1882** [aquasecurity/libbpfgo#188]

**Comment by rafaeldtinoco** [comment]
If you play with:

https://github.com/aquasecurity/libbpfgo/blob/main/libbpfgo.go#L36

(and return vfprintf() in all cases, you will get all the debug information from libbpf during libbpfgo execution as well.

I think we're missing an automated way of setting different loglevels though.

**Comment by rafaeldtinoco** [comment]
This is a duplicate of https://github.com/aquasecurity/libbpfgo/issues/55
