### ISSUE TITLE
How to use Memory-mapping bpf map by libbpfgo

### ISSUE THREAD

**Issue by dbfancier** [aquasecurity/libbpfgo#189]
I found out that the Linux kernel supports memory-mapping BPF maps, but I'm not sure how to use it in libbpfgo, are there any examples. Thanks

**Comment by rafaeldtinoco** [comment]
@dbfancier best place for your to learn is from our selftests at:

https://github.com/aquasecurity/libbpfgo/tree/main/selftest

You're probably referring to how you can transmit events from kernel to userland:

https://github.com/aquasecurity/libbpfgo/tree/main/selftest/perfbuffers
or
https://github.com/aquasecurity/libbpfgo/tree/main/selftest/ringbuffers

but you may also be referring to how to access shared data among kernel and userland (through eBPF maps):

https://github.com/aquasecurity/libbpfgo/tree/main/selftest/map-update

I'll close this as this is not an issue in libbpfgo.
