### ISSUE TITLE
Fail to get the pinned bpf map

### ISSUE THREAD

**Issue by leiqi96** [aquasecurity/libbpfgo#190]
A map name is defined as being longer than BPF_OBJ_NAME_LEN. If a userspace program load bpf object file for the scond time, it will fail to get the bpf map by the map actual name.

I have wrote some code to test this situcation. 
Link: https://github.com/leiqi96/libbpf-fix/tree/go

This is related to libbpf. I have submitted patch to libbpf.
Link: https://git.kernel.org/bpf/bpf-next/c/bf3f00378524

Maybe libbpfgo can use the latest libbpf or  limit the length of the  bpf_map name

**Comment by geyslan** [comment]
> Maybe libbpfgo can use the latest libbpf or limit the length of the bpf_map name

@grantseltzer we're already using libbpf with the mentioned [changes](https://github.com/libbpf/libbpf/commit/9b6f4eb1570c219474f6029caea71584d7a2188a).

I tested this with current libbpfgo:

```go
	pinnedMap1, err := bpfModule.GetMap("process_pinned_map_1")
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(-1)
	} else {
		fmt.Printf("success:get bpf name name %s %d\n", pinnedMap1.Name(), pinnedMap1.FileDescriptor())
	}

	pinnedMap2, err := bpfModule.GetMap("process_pinned_map_2")
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(-1)
	} else {
		fmt.Printf("success:get bpf name name %s %d\n", pinnedMap2.Name(), pinnedMap2.FileDescriptor())
	}
```

```c
struct {
	__uint(type, BPF_MAP_TYPE_HASH);
...
} process_pinned_map_1 SEC(".maps");

struct {
	__uint(type, BPF_MAP_TYPE_ARRAY);
...
} process_pinned_map_2 SEC(".maps");
```

```bash
$ sudo bpftool map   
5: hash  name process_pinned_  flags 0x0
        key 4B  value 4B  max_entries 1024  memlock 8192B
        btf_id 364
6: array  name process_pinned_  flags 0x0
        key 4B  value 4B  max_entries 1024  memlock 8192B
        btf_id 364
```

And got:

```
success:get bpf name name process_pinned_map_1 5
success:get bpf name name process_pinned_map_2 6
```

So, if you don't think otherwise (like limiting the name to BPF_OBJ_NAME_LEN), I bet this is no longer an issue.

**Comment by grantseltzer** [comment]
@leiqi96 Thanks for reporting this, and for making the change upstream! Sorry it took so long for us comment, I was on vacation when you reported it.

@geyslan Thanks for checking this out, seems like we're in the clear. Closing!
