### ISSUE TITLE
libbpf_num_possible_cpus support ?

### ISSUE THREAD

**Issue by rafaeldtinoco** [aquasecurity/libbpfgo#195]
Maybe we should add support to:

![image](https://user-images.githubusercontent.com/7395852/180629121-c9913340-3c72-4938-a7c9-776b1288c04e.png)

and improve the experience when trying to get which CPUs are online..

Discussion at: https://github.com/aquasecurity/libbpfgo/issues/191

**Comment by rafaeldtinoco** [comment]
All libbpf/libbpfgo users relying in per CPU map feature will have to do some logic like this:

![image](https://user-images.githubusercontent.com/7395852/180629182-ac462f93-5e55-4896-ad91-3941db76cda5.png)

**Comment by javierhonduco** [comment]
Adding this API would be great! Right now some projects rely on Go's [runtime library](https://pkg.go.dev/runtime#NumCPU), but I am not sure if that accounts for offline CPUs as libbpf does

**Comment by rafaeldtinoco** [comment]
> Adding this API would be great! Right now some projects rely on Go's [runtime library](https://pkg.go.dev/runtime#NumCPU), but I am not sure if that accounts for offline CPUs as libbpf does

No it does not I think. Knowing how many CPUs are enabled or not is not enough for when dealing with per-cpu maps. We need to know exact CPU number that is online to know from which buffer to pick the info afaict.

**Comment by javierhonduco** [comment]
Makes sense, will move to `libbpf_num_possible_cpus` as soon as it's available 😄

**Comment by v-thakkar** [comment]
If nobody is working on this, I'll be happy to tackle this. It'll be nice to use libbpf_num_possible_cpus instead of runtime.NumCPU() in parca-agent especially because it doesn't seem to be reflecting the changes to the CPU allocation after the process has started.
