### ISSUE TITLE
BPFMap.Name() should return an optional error

### ISSUE THREAD

**Issue by grantseltzer** [aquasecurity/libbpfgo#220]
BPFMap.Name() calls `bpf_map__name` which will return NULL if the underlying map is NULL. We have a check for the return being nil, but perhaps we should throw an error to surface this issue to the API user.

**Comment by geyslan** [comment]
The NULL return is related to NULL maps, not names. NULL name checks `!map->name` are all error checks. An error throw is welcome, indeed. I could pick this if you don't mind.

**Comment by grantseltzer** [comment]
@geyslan So do you agree that surfacing an error would be good? It feels weird since it's a 'getter' method but it could be useful if someone is confused about why the name is an empty string and not realizing that the map is NULL.

If you agree you handling it would be great, though I wouldn't want to merge it until we agree on the roadmap towards libbpfgo 1.0 (we'll merge API breaking changes right before then)

**Comment by geyslan** [comment]
> @geyslan So do you agree that surfacing an error would be good? It feels weird since it's a 'getter' method but it could be useful if someone is confused about why the name is an empty string and not realizing that the map is NULL.

Yeah. I do, even it being odd for a getter. As you mentioned, the error can be helpful. But I wonder if it's possible to get a NULL map from within libbpfgo. The sanity check in libbpf seems more related to C pointer handling. WDYT?

**Comment by geyslan** [comment]
> The sanity check in libbpf seems more related to C pointer handling. WDYT?

@grantseltzer working on https://github.com/aquasecurity/libbpfgo/pull/230 I'm more convinced that the `bpf_map__name` check is more to be a sanity check of the map pointer to be dereferenced in the next lines. I think that way once `bpf_program__name` version doesn't check prog pointer, since it's always set.

> @geyslan So do you agree that surfacing an error would be good? It feels weird since it's a 'getter' method but it could be useful if someone is confused about why the name is an empty string and not realizing that the map is NULL.

Rethinking that, I suppose that a wrapped libbpf map must always be **not** NULL during the program lifetime. And whether it someway happens that it be NULL, it should have to be checked and treated not in the Name() method.

Said that, If you agree, we could reduce it this way:

```diff
 func (b *BPFMap) Name() string {
-       cs := C.bpf_map__name(b.bpfMap)
-       if cs == nil {
-               return ""
-       }
-       s := C.GoString(cs)
-       return s
+       return C.GoString(C.bpf_map__name(b.bpfMap))
 }
```

Going further, if we define goals to make libbpfgo even more reliable (returning errors accordingly), I guess we should do things like:

```go
func (b *BPFMap) Name() (string, error) {
	if b == nil || b.bpfMap == nil {
		return "", fmt.Errorf("BPF map is null")
	}
	return C.GoString(C.bpf_map__name(b.bpfMap)), nil
}
```

**Comment by geyslan** [comment]
@grantseltzer @rafaeldtinoco If you agree, we can change this issue to standardize the entire lib to check pointer receivers and inner references as well as return proper errors (API-break).

> Going further, if we define goals to make libbpfgo even more reliable (returning errors accordingly), I guess we should do things like:

```go
func (b *BPFMap) Name() (string, error) {
	if b == nil {
		return "", fmt.Errorf("BPFMap is nil")
	}
	if b.bpfMap == nil {
		return "", fmt.Errorf("libbpf bpf_map is nil")
	}
	return C.GoString(C.bpf_map__name(b.bpfMap)), nil
}
```

**Comment by geyslan** [comment]
Closing this since it wasn't planned.
