### ISSUE TITLE
SetAttachType should return an error

### ISSUE THREAD

**Issue by grantseltzer** [aquasecurity/libbpfgo#224]
`bpf_program__set_expected_attach_type()` returns an error so should its wrapper

**Comment by geyslan** [comment]
Same effort: #223

**Comment by CodePrometheus** [comment]
@geyslan hello, I'd like to try these two modifications, could you assign them to me?

**Comment by geyslan** [comment]
@CodePrometheus Thank you for applying for the task. Any doubts, please let us know.
