### ISSUE TITLE
Make a pre-made vmlinux.h available in tree

### ISSUE THREAD

**Issue by geyslan** [aquasecurity/libbpfgo#242]
- [x] Remove libbpfgo Makefile bpftool requirement.
- [x] Add caped vmlinux.h for selftests.

Originated from: https://github.com/aquasecurity/libbpfgo/pull/239#discussion_r966987168
Related: #177 #254

**Comment by ShubhamPalriwala** [comment]
Hey, so for this. I should run `bpftool btf dump file /sys/kernel/btf/vmlinux format c > vmlinux.h` locally and generate the vmlinux.h and then add it to our root directory as `vmlinux.h` and add a flag in the makefile if one wants to specify a custom `vmlinux.h` right?

Can I take this up?

**Comment by ShubhamPalriwala** [comment]
@geyslan @grantseltzer Can you let me know if the above approach is good to go? Or am I missing something?
