### ISSUE TITLE
How do I remove memory limits？

### ISSUE THREAD

**Issue by sunhaotian0122** [aquasecurity/libbpfgo#247]
In old version, there is bump_memlock_rlimit() to remove limits, but I can not find the Similar functions now. So, once I run the program, I get the following error message.

```
libbpf: prog 'kprobe_execve': BPF program load failed: Operation not permitted
libbpf: permission error while running as root; try raising 'ulimit -l'? current value: 64.0 KiB
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xffffa448c74c]
```

In addition, could you please update the selftest.

**Comment by geyslan** [comment]
@sunhaotian0122 have you updated libbpf to 1.0? `bumpMemlockRlimit()` was removed due to 1.0 doing that automatically.

See: https://github.com/aquasecurity/libbpfgo/commit/b3f2e055fe69c074e511b08b0bfa938180339358

**Comment by sunhaotian0122** [comment]
Yes, I updated libbpf to 1.0. But, it doesn't seem to do it automatically. I temporarily solved it through `ulimit -l 65535`. However, I want to solve it by code. How does libbpf-1.0 do that automatically？ I try `libbpfgo.SetStrictMode(libbpfgo.LibbpfStrictModeAutoRlimitMemlock)`, although I don't know whether it is useful, But it doesn't work.

**Comment by geyslan** [comment]
Perhaps you are using an old system libbpf. Please, check its version. More info about the automatic memory bump: https://github.com/libbpf/libbpf/issues/369 and https://github.com/libbpf/libbpf/commit/216eaa760edf06f3521d5d49a419515607c1f38e

I would suggest you clear go caches as well, building libbpfgo again., since it could be retaining old references.

**Comment by geyslan** [comment]
@sunhaotian0122 is this issue still relevant? Let me know if we can help you.

**Comment by geyslan** [comment]
@sunhaotian0122 Closing this due to the lack of info. If still relevant it can be reopened at any time.
