### ISSUE TITLE
Make libbpf_print_fn callback logic clearer

### ISSUE THREAD

**Issue by geyslan** [aquasecurity/libbpfgo#276]
By making the args and format checks explicit, the libbpf_print_fn logic can be clearer and filter out only those errors that we strictly defined.

`"libbpf: Kernel error message: %s\n"`
`%s` = `"Esclusivity flag on"`
https://github.com/libbpf/libbpf/blob/68e6f83f223ebf3fbf0d94c0f4592e5e6773f0c1/src/nlattr.c#L192

`"libbpf: prog '%s': failed to attach to %s: %s\n"`
1st `%s` = `cgroup_skb_ingress` or `cgroup_skb_egress`
2nd `%s` = `cgroup`
3nd `%s` = `Invalid argument`
https://github.com/libbpf/libbpf/blob/eb9b5c567d59931698e83e2b26ff77eb61f33f8c/src/libbpf.c#L11333

---

Related discussion: https://github.com/aquasecurity/libbpfgo/pull/270#issuecomment-1346810443

**Comment by rafaeldtinoco** [comment]
I did miss it indeed, could u rebase on top of the one recently merged, sorry about it. @geyslan this is all yours (if you'd like =D).

**Comment by javierhonduco** [comment]
I won't have much bandwidth for this in the next ~3 weeks, unfortunately, but feel free to use it. Thanks for landing the current fix! :) We just updated to get these changes and will monitor the stability on our side

**Comment by rafaeldtinoco** [comment]
Thanks @javierhonduco, we might take a little long as well (EOY time offs and such). But will keep the issue in the next fixes milestone so we don't forget!
