### ISSUE TITLE
Failed to compile the tc program. __sk_buff could not be found

### ISSUE THREAD

**Issue by yuansonghe0123** [aquasecurity/libbpfgo#290]
error: use of undeclared identifier '__sk_buff'
    process = bpf_ringbuf_reserve(&events, sizeof(__sk_buff), ringbuffer_flags);
                                                  ^
1 error generated.
make: *** [/home/ysh/Nexus/libbpfgo/Makefile:32：c2bpf] error 1

**Comment by geyslan** [comment]
@yuansonghe0123 could you provide more information about the error you are experiencing?

In the meantime, I suggest you take a look at https://github.com/aquasecurity/libbpfgo/tree/main/selftest folders, specifically in https://github.com/aquasecurity/libbpfgo/tree/main/selftest/tc one.

Inside `tc` folder, run `make` and `make run`, certainly you'll get:

![image](https://user-images.githubusercontent.com/3372117/218101721-9609fbf8-e0e6-40bf-b2e8-45728da49646.png)

Without the necessary information, if I could give you one piece of advice it would be to build libbpfgo statically.

More:

- https://github.com/aquasecurity/libbpfgo#building
- https://github.com/aquasecurity/libbpfgo/issues/289#issuecomment-1424340549

**Comment by yuansonghe0123** [comment]
thanks for your help!!!

**Comment by geyslan** [comment]
@yuansonghe0123, anything else feel free to ask.
