### ISSUE TITLE
BPFProgramTypeIsSupported(bpf.BPFProgTypeSocketFilter) returns true

### ISSUE THREAD

**Issue by MaciekLeks** [aquasecurity/libbpfgo#291]
Hello,

Function `BPFProgramTypeIsSupported` returns` true` for socket related program type `BPFProgramTypeIsSupported` but looking inside the module code I can't see such a possibility to attach `socket` program to a socket. I missed something or it's a bug?

module version: `github.com/aquasecurity/libbpfgo v0.4.5-libbpf-1.0.1`

**Comment by mozillazg** [comment]
@MaciekLeks This function is use for check features of the host Linux kernel, not for check libbpfgo.
