### ISSUE TITLE
Version `v0.4.8.1-libbpf-1.2.0` is not go module / semver compatible

### ISSUE THREAD

**Issue by saschagrunert** [aquasecurity/libbpfgo#328]
Using that tag in go modules will always resolve into `v0.4.8-libbpf-1.2.0.0.20230509162948-80f41e18e690`, which is more a cosmetic but irritating change. Do you think that it's possible to stick to plain semver instead?

**Comment by saschagrunert** [comment]
It's okay we can wait and I'd see this issue as resolved with a v0.4.9 upcoming release. :)

**Comment by geyslan** [comment]
@saschagrunert has the https://github.com/aquasecurity/libbpfgo/releases/tag/v0.4.9-libbpf-1.2.0 solved this issue?

**Comment by saschagrunert** [comment]
Yep, thank you!
