### ISSUE TITLE
Remove kprobe legacy logic once upstream accepts it

### ISSUE THREAD

**Issue by rafaeldtinoco** [aquasecurity/libbpfgo#34]
Discussing **libbpf: add legacy kprobe attach support** at:

https://github.com/libbpf/libbpf/issues/317

libbpfgo "cgo: attach_kprobe_legacy" and "doAttachKprobeLegacy" logic should be removed once libbpf accepts that patch.

**Comment by rafaeldtinoco** [comment]
Latest proposal at [LORE](https://lore.kernel.org/bpf/20210625044459.1249282-1-rafaeldtinoco@gmail.com/) thread.

**Comment by rafaeldtinoco** [comment]
Latest proposal at:

https://lore.kernel.org/bpf/20210801051123.3822498-1-rafaeldtinoco@gmail.com/

already to be applied on top of the:

[PATCH v3 bpf-next 00/14] BPF perf link and user-provided bpf_cookie

patch set from Andrii. It will need to wait until that patch set is merged. It correctly replaces libbpfgo legacy kprobe implementation embedded at libbpfgo.go source code (for current libbpf upstream branch).

**Comment by rafaeldtinoco** [comment]
Commit got merged in for-next (bpf-next):

```
commit 467b3225553a (HEAD -> rafaeldtinoco, origin/master, origin/for-next, origin/HEAD)
Author: Rafael David Tinoco <rafaeldtinoco@gmail.com>
Date:   Sun Sep 12 03:48:44 2021

    libbpf: Introduce legacy kprobe events support

    Allow kprobe tracepoint events creation through legacy interface, as the
    kprobe dynamic PMUs support, used by default, was only created in v4.17.

    Store legacy kprobe name in struct bpf_perf_link, instead of creating
    a new "subclass" off of bpf_perf_link. This is ok as it's just two new
    fields, which are also going to be reused for legacy uprobe support in
    follow up patches.

    Signed-off-by: Rafael David Tinoco <rafaeldtinoco@gmail.com>
    Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
    Link: https://lore.kernel.org/bpf/20210912064844.3181742-1-rafaeldtinoco@gmail.com
```

It will get into bpf-next and, eventually, into libbpf (github). We will be able to get rid of legacy kprobe functions.

**Comment by rafaeldtinoco** [comment]
Alright, the legacy kprobe logic just got merged into libbpf:

https://github.com/libbpf/libbpf/commit/749b3942a09300a570198bc27814405ab92607ae

and into bpf-next tree. Andrii has already refactored it to support legacy uprobes as well as some fixes.

We're ready for the legacy kprobe specific functions removal in libbpfgo.

**Comment by yanivagman** [comment]
I think we should wait with that until libbpf 0.6.0 (which should include the patch) will be out

**Comment by yanivagman** [comment]
@rafaeldtinoco I think we can now remove those functions, can't we?
