### ISSUE TITLE
LIBBPF_MAJOR_VERSION missing

### ISSUE THREAD

**Issue by SamYuan1990** [aquasecurity/libbpfgo#392]
LIBBPF_MAJOR_VERSION function is missing on ubuntu server. if we just install ubuntu distribution version as 0.5
```
root@d82887bb353b:/# dpkg -l | grep libbpf
ii  libbpf-dev:amd64        1:0.5.0-1ubuntu22.04.1                  amd64        eBPF helper library (development files)
ii  libbpf0:amd64           1:0.5.0-1ubuntu22.04.1                  amd64        eBPF helper library (shared library)
```
it seems the `LIBBPF_MAJOR_VERSION` is only available after 0.6 version of libbpf, is that possible to avoid manual build for libbpf binary packages?

**Comment by geyslan** [comment]
Closing this because it doesn't seem like a problem.
