### ISSUE TITLE
Error compiling go programme

### ISSUE THREAD

**Issue by sidahmedabdelillah** [aquasecurity/libbpfgo#400]
Hello. I am working demonstration for ebpf.

This is the go programme
```go
package main

import "C"

import (
	"fmt"
	"os"
	"unsafe"

	bpf "github.com/aquasecurity/libbpfgo"
)

type Target struct {
	Pid  uint32
	Comm [16]byte
	Path [256]byte
}

func main() {
	bpfModule, err := bpf.NewModuleFromFile("ebpf.o")
	if err != nil {
		panic(err)
	}
	defer bpfModule.Close()
	if err := bpfModule.BPFLoadObject(); err != nil {
		panic(err)
	}
	targetMap, err := bpfModule.GetMap("target")
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(-1)
	}

	// update the map

	key := uint32(0x1337)
	var val Target
	copy(val.Comm[:], "procname")
	copy(val.Path[:], "/home/azureuser/ebpf/secret")
	val.Pid = uint32(9999)
	keyUnsafe := unsafe.Pointer(&key)
	valueUnsafe := unsafe.Pointer(&val)
	targetMap.Update(keyUnsafe, valueUnsafe)
}
```
I compiled the bpf using this commande
```bash
clang -g -O2 -c -target bpf -o ebpf.o ebpf.c
```
and tried building the go using this 
`
CC=gcc CGO_CFLAGS="-I /usr/include/bpf" CGO_LDFLAGS="/usr/lib64/libbpf.a" sudo go build -o libbpfgo-prog
`
I got the error 
`
../../../go/pkg/mod/github.com/aquasecurity/libbpfgo@v0.6.0-libbpf-1.3/map-common.go:51:39: could not determine kind of name for C.BPF_MAP_TYPE_BLOOM_FILTER
`

**Comment by geyslan** [comment]
> `CGO_CFLAGS="-I /usr/include/bpf"`

It seems you're using the installed libbpf include and not the one provided by libbpfgo. I guess your system libbpf version hasn't support to `BPF_MAP_TYPE_BLOOM_FILTER` (introduced by https://github.com/libbpf/libbpf/commit/168cf9b8ae24afd779f2976c76c6a8628540a3e4).

Take a look at libbpfgo selftest building process for more information:

https://github.com/aquasecurity/libbpfgo/blob/90dbffffbdabd70bb8e834b8777bf12186e1ae8c/selftest/common/Makefile#L17-L18

**Comment by geyslan** [comment]
Closing as it doesn't seem a problem. Please reopen it if relevant.
