### ISSUE TITLE
TcHook.Detach() always raises the `failed to detach tc hook: invalid argument` error.

### ISSUE THREAD

**Issue by mozillazg** [aquasecurity/libbpfgo#420]
`TcHook.Detach()` always raises the `failed to detach tc hook: invalid argument` error.

```diff
$ git diff
diff --git a/selftest/tc/main.go b/selftest/tc/main.go
index 0174eb1..4137fc2 100644
--- a/selftest/tc/main.go
+++ b/selftest/tc/main.go
@@ -61,6 +61,12 @@ func main() {
                fmt.Fprintln(os.Stderr, err)
                os.Exit(-1)
        }
+       defer func() {
+               if err := hook.Detach(&tcOpts); err != nil {
+                       fmt.Fprintln(os.Stderr, err)
+                       os.Exit(-1)
+               }
+       }()
 
        eventsChannel := make(chan []byte)
        rb, err := bpfModule.InitRingBuf("events", eventsChannel)
```

```
$ make run
...
failed to detach tc hook: invalid argument
[!] ERROR: test error
```

test with the main branch: [a55c024](https://github.com/aquasecurity/libbpfgo/commit/a55c0244e1bcc89e1b0ea191368dda37c5dd0aa0)

**Comment by geyslan** [comment]
@mozillazg I couldn't reproduce it in the vagrant VM, only got this:

`libbpf: object 'main': failed (-22) to create BPF token from '/sys/fs/bpf', skipping optional step...`

The unique detected besides that type is `libbpf: map 'tester': failed to create: Invalid argument(-22)` in `selftest/map-autocreate`: https://github.com/aquasecurity/libbpfgo/actions/runs/8570253314/job/23488218928#step:4:1585

What's your testing env?

**Comment by chentao-kernel** [comment]
@geyslan @mozillazg   hi, geyslan, i think it is same issue with 211, and i also add test case again.

**Comment by chentao-kernel** [comment]
> @geyslan @mozillazg hi, geyslan, i think it is same cause with #421, and i also add test case for it.

**Comment by chentao-kernel** [comment]
> @mozillazg I couldn't reproduce it in the vagrant VM, only got this:我无法在流浪者虚拟机中重现它，只得到这个：
> 
> `libbpf: object 'main': failed (-22) to create BPF token from '/sys/fs/bpf', skipping optional step...`
> 
> The unique detected besides that type is `libbpf: map 'tester': failed to create: Invalid argument(-22)` in `selftest/map-autocreate`: https://github.com/aquasecurity/libbpfgo/actions/runs/8570253314/job/23488218928#step:4:1585除该类型外，检测到的唯一值 `libbpf: map 'tester': failed to create: Invalid argument(-22)` 为 `selftest/map-autocreate` ： https://github.com/aquasecurity/libbpfgo/actions/runs/8570253314/job/23488218928#step:4:1585
> 
> What's your testing env?您的测试环境是什么？

@geyslan, it it not the same issue with #420
it may be caused by the ebpf new feature of token

**Comment by mozillazg** [comment]
Closed via https://github.com/aquasecurity/libbpfgo/pull/422
