### ISSUE TITLE
Static builds with newer libelf require `-l zstd`

### ISSUE THREAD

**Issue by bobrik** [aquasecurity/libbpfgo#429]
Ubuntu 24.04 links `libelf.so` against `libzstd.so`. This doesn't matter at all for dynamically linked builds, but if you want a link a fully static binary, you need `-l zstd` in `CGO_LDFLAGS`. Currently `libbpfgo` only has:

```
#cgo LDFLAGS: -lelf -lz
```

I worked around this in `ebpf_exporter`:

* https://github.com/cloudflare/ebpf_exporter/blob/b908d3ba7/Makefile#L34-L37

```makefile
# If libelf is new and it links to zstd, then zstd needs to be manually linked in.
ifneq ($(shell ldd $(shell /sbin/ldconfig -n -p | grep libelf.so.1 | awk '{ print $$NF }') | grep zstd),)
CGO_LDFLAGS := $(CGO_LDFLAGS) -l zstd
endif
```

Perhaps there's a better way in `libbpfgo` itself.

**Comment by geyslan** [comment]
@bobrik thanks for reporting this.

@trvll is it the same that you facing? Could you test it?

**Comment by bobrik** [comment]
I think you can replicate this in Github actions by bumping Ubuntu 22.04 to 24.04.

**Comment by geyslan** [comment]
Thanks @bobrik. zstd is indeed a requirement depending on the environment when a static build is the target. I'll be bumping this repo as soon as possible and tackling that.
