### ISSUE TITLE
libbpf_print_fn function to display CO-RE relocations debug information

### ISSUE THREAD

**Issue by rafaeldtinoco** [aquasecurity/libbpfgo#55]
I had already in mind that libbpf_print_fn could be used to display bpf object load debug messages from libbpf, specially for us to debug CO-RE rellocations issues. After the following comment from upstream:

https://github.com/aquasecurity/tracee/pull/950#issuecomment-904057441

we may also need to filter out some other errors (which I'll investigate in this issue altogether).

**Comment by geyslan** [comment]
This's being tackled by https://github.com/aquasecurity/libbpfgo/pull/284 (filtering callbacks).
