### ISSUE TITLE
Print debug messages if debug flag was chosen

### ISSUE THREAD

**Issue by yanivagman** [aquasecurity/libbpfgo#6]
We currently only print libbpf messages which have WARN level.
If debug flag was given, we should also print debug messages from libbpf.

Example:
https://github.com/libbpf/libbpf-bootstrap/blob/master/src/bootstrap.c#L62

**Comment by rafaeldtinoco** [comment]
Duplicate of: https://github.com/aquasecurity/libbpfgo/issues/55
Related: https://github.com/aquasecurity/libbpfgo/issues/188

**Comment by geyslan** [comment]
This is being tackled by https://github.com/aquasecurity/libbpfgo/pull/284, via filtering callbacks.
