### ISSUE TITLE
helpers: Discover BTFinfo from inside a container

### ISSUE THREAD

**Issue by yanivagman** [aquasecurity/libbpfgo#60]
We currently look for the distro info in `/etc/os-release` (https://github.com/aquasecurity/libbpfgo/blob/main/helpers/btfinfo.go#L91).
When we run from inside a container, this file may represent a different distro, which will give us the wrong BTFinfo.
We need to be able to support an external /etc/os-release file as an argument, so it will be possible to point to a mounted file instead of the hardcoded /etc/os-release

**Comment by rafaeldtinoco** [comment]
TODO: add an option to override whatever the discovery process is doing.

**Comment by rafaeldtinoco** [comment]
My recent pull request allows us to bind mount /etc/os-release to something like /etc/os-release-host in the container and feed that to tracee using TRACEE_OSRELEASE_FILE environment variable. If not bound, we can also opt to create a fake os-release file with the host information and provide that as well. 

> I'm going to add cmdline support for providing ID and VERSION_ID values from os-release directly. If those are provided then tracee won't even read /etc/os-release OR TRACEE_OSRELEASE_FILE.
