### ISSUE TITLE
Link Detach support is missing

### ISSUE THREAD

**Issue by geyslan** [aquasecurity/libbpfgo#66]
I've just spoke to @rafaeldtinoco and it might there be a need for us to support detach/unloading of specific ebpf programs links without to close the object (and consequently its other relations).

**Comment by geyslan** [comment]
`bpf_link__detach(struct bpf_link *link)`

https://github.com/libbpf/libbpf/blob/72fd44da537aa7c5819cf15ea6ddc15d641cc1d6/src/libbpf.h#L242

**Comment by rafaeldtinoco** [comment]
This is important also for our 'reload' feature in tracee (when we may need to detach a link, unload a program, load another program, attach it, etc). And makes sense. Would you provide a PR for it ?

**Comment by geyslan** [comment]
Grand. Please assign this to me.

**Comment by rafaeldtinoco** [comment]
Note to myself: when kprobe legacy logic is removed - after being merged upstream - make sure that our unlink is good for legacy attachments as well (https://github.com/aquasecurity/libbpfgo/issues/34).

**Comment by rafaeldtinoco** [comment]
Discussion happening in: https://github.com/aquasecurity/libbpfgo/pull/78

**Comment by geyslan** [comment]
I suppose this can be closed.
