### ISSUE TITLE
Improve perf and ring buffers performance

### ISSUE THREAD

**Issue by yanivagman** [aquasecurity/libbpfgo#80]
It is well known that cgo has bad performance when calling c code, and even worse when calling go callbacks from c (see, for example, https://about.sourcegraph.com/go/gophercon-2018-adventures-in-cgo-performance/).

This is actually not a problem for most of the use cases of libbpfgo, where we just need to load a program and attach it, or update a map, as these operations are not that frequent. It may become a problem, however, when we need to poll for events coming from the kernel through one of the perf/ring buffers, as these are much more frequent.

Suggestion: for buffers polling (either perf or ring buffers) let's implement the logic in pure go. These functions can be added as an alternative API for the already existing functions, and will offer high performance where needed.

Specifically, these are the libbpf functions that we will need to implement: `C.perf_buffer__poll()` and `C.ring_buffer_poll()` (both are called by the PerfBuffer/RingBuffer `poll()` function)

**Comment by longlihale** [comment]
> It is well known that cgo has bad performance when calling c code, and even worse when calling go callbacks from c (see, for example, https://about.sourcegraph.com/go/gophercon-2018-adventures-in-cgo-performance/).
> 
> This is actually not a problem for most of the use cases of libbpfgo, where we just need to load a program and attach it, or update a map, as these operations are not that frequent. It may become a problem, however, when we need to poll for events coming from the kernel through one of the perf/ring buffers, as these are much more frequent.
> 
> Suggestion: for buffers polling (either perf or ring buffers) let's implement the logic in pure go. These functions can be added as an alternative API for the already existing functions, and will offer high performance where needed.
> 
> Specifically, these are the libbpf functions that we will need to implement: `C.perf_buffer__poll()` and `C.ring_buffer_poll()` (both are called by the PerfBuffer/RingBuffer `poll()` function)

hello, The conclusions of 2018 are not necessarily appropriate for now, 
for example, https://about.sourcegraph.com/go/gophercon-2018-adventures-in-cgo-performance/).

**Comment by itaysk** [comment]
duplicate of #42
