### ISSUE TITLE
Remove unused "GetUnsafePointer()" API function

### ISSUE THREAD

**Issue by grantseltzer** [aquasecurity/libbpfgo#98]

**Comment by kakkoyun** [comment]
@grantseltzer What was the reason behind the introduction of this method? Are there any things need to be considered?

I'm happy to take this one.

**Comment by grantseltzer** [comment]
@kakkoyun You can get some background on why we removed usage of it here: https://github.com/aquasecurity/libbpfgo/pull/32

To summarize, it was use to validate data types for BPF maps, but there was no need to do that so we removed it.

Completing this issue is  just removing the function definition, if you don't mind, it's a very welcome and appreciated contribution!
